export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const CLEAR_REGISTER = "CLEAR_REGISTER";

export const CLEAR_USERS = "CLEAR_USERS";
export const GET_DOMESTIC_LOGS = "GET_DOMESTIC_LOGS";
export const USER_LOGOUT = "USER_LOGOUT";
export const SUCCESS_CREATE = "SUCCESS_CREATE";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const GET_INTERNATIONAL_LOGS = "GET_INTERNATIONAL_LOGS";
export const LOG_CLICKED = "LOG_CLICKED";

export const LOG_LOADING = "LOAD_LOADING";

export const ADD_DOMESTIC_LOG = "ADD_DOMESTIC_LOG";
export const ADD_INTERNATIONAL_LOG = "ADD_INTERNATIONAL_LOG";
export const ADD_STATUS = "ADD_STATUS";

export const DELETE_STATUS = "DELETE_STATUS";
export const DELETE_LOG = "DELETE_LOG";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const RECEIVE_REPLY = "RECEIVE_REPLY";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const GET_WEATHER = "GET_WEATHER";

export const SHOW_ALERT = "SHOW_ALERT";

export const SET_ACTIVITY_LOADING = "SET_ACTIVITY_LOADING";
export const GET_DOMESTIC_ACTIVITIES = "GET_DOMESTIC_ACTIVITIES";
export const GET_INTERNATIONAL_ACTIVITIES = "GET_INTERNATIONAL_ACTIVITIES";
